package com.java.practice.ems.employee.dto;

import com.java.practice.ems.employee.entity.Employee;
import com.java.practice.ems.employee.entity.EmployeeStatus;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * ╔══════════════════════════════════════════════════════════════════════════════╗
 * ║ EmployeeResponse — Outbound DTO (Java 21 Record) ║
 * ╚══════════════════════════════════════════════════════════════════════════════╝
 *
 * <h2>SINGLE RESPONSIBILITY: ENTITY vs RESPONSE DTO</h2>
 *
 * <p>
 * This Record controls EXACTLY what data leaves the application boundary.
 * It acts as an "anti-corruption layer" between the internal domain model
 * and external API consumers:
 * </p>
 *
 * <table>
 * <tr>
 * <th>Concern</th>
 * <th>Entity (Employee)</th>
 * <th>DTO (EmployeeResponse)</th>
 * </tr>
 * <tr>
 * <td>ID field</td>
 * <td>Generated by DB</td>
 * <td>Exposed to client</td>
 * </tr>
 * <tr>
 * <td>Password hash</td>
 * <td>Stored</td>
 * <td>NEVER exposed</td>
 * </tr>
 * <tr>
 * <td>Audit timestamps</td>
 * <td>Managed by Hibernate</td>
 * <td>Read-only for client</td>
 * </tr>
 * <tr>
 * <td>Lazy associations</td>
 * <td>Proxied (may cause N+1)</td>
 * <td>Eagerly resolved</td>
 * </tr>
 * <tr>
 * <td>Internal flags</td>
 * <td>Used by service logic</td>
 * <td>Hidden from client</td>
 * </tr>
 * </table>
 *
 * <h2>JAVA 21 RECORDS AS RESPONSE DTOs</h2>
 *
 * <p>
 * Records are particularly well-suited for response DTOs because:
 * </p>
 * <ul>
 * <li><strong>Immutable:</strong> The response cannot be accidentally modified
 * after
 * the service layer creates it — what goes into JSON serialization is exactly
 * what the service intended.</li>
 * <li><strong>Self-documenting:</strong> The record header IS the API schema —
 * each
 * parameter is a field in the JSON response. No need for separate
 * documentation.</li>
 * <li><strong>Value equality:</strong> In tests, you can assert:
 * {@code assertEquals(expectedResponse, actualResponse)} and it compares ALL
 * fields,
 * unlike entities which compare only by ID.</li>
 * <li><strong>Compact:</strong> This entire DTO with 11 fields, constructor,
 * getters,
 * equals/hashCode, toString, AND a factory method is ~80 lines. A traditional
 * class would be ~200+ lines.</li>
 * </ul>
 *
 * @param id         Unique identifier (database-generated)
 * @param firstName  Employee's first name
 * @param lastName   Employee's last name
 * @param email      Unique email address
 * @param phone      Contact phone number (may be null)
 * @param department Department name (may be null)
 * @param jobTitle   Job title/position (may be null)
 * @param salary     Monthly salary (may be null for privacy in some views)
 * @param hireDate   Employment start date (may be null)
 * @param status     Current employment status
 * @param createdAt  Record creation timestamp (audit)
 * @param updatedAt  Last modification timestamp (audit)
 */
public record EmployeeResponse(
        Long id,
        String firstName,
        String lastName,
        String email,
        String phone,
        String department,
        String jobTitle,
        BigDecimal salary,
        LocalDate hireDate,
        EmployeeStatus status,
        LocalDateTime createdAt,
        LocalDateTime updatedAt) {

    // ═══════════════════════════════════════════════════════════════════════════
    // FACTORY METHOD — Entity → DTO Mapping
    // ═══════════════════════════════════════════════════════════════════════════
    //
    // Why a static factory method instead of a constructor or external mapper?
    //
    // 1. ENCAPSULATION: The mapping logic lives WITH the DTO, not scattered
    // across services. If a new field is added to the response, you change
    // ONE place — this method.
    //
    // 2. READABILITY: Service code reads naturally:
    // return EmployeeResponse.from(savedEmployee);
    // instead of:
    // return new EmployeeResponse(e.getId(), e.getFirstName(), ...);
    //
    // 3. SINGLE RESPONSIBILITY: The DTO knows how to construct itself from
    // an entity. The service layer doesn't need to know the DTO's field order.
    //
    // For complex mappings (multiple entities → one DTO), consider MapStruct,
    // which generates type-safe mappers at compile time with zero runtime cost.
    //

    /**
     * Creates an EmployeeResponse from a JPA Employee entity.
     * <p>
     * This method is the ONLY bridge between the persistence layer and the API
     * layer.
     * All field transformations (e.g., formatting, filtering sensitive data) happen
     * here.
     *
     * @param employee the JPA entity (must not be null)
     * @return an immutable DTO ready for JSON serialization
     * @throws NullPointerException if employee is null
     */
    public static EmployeeResponse from(Employee employee) {
        return new EmployeeResponse(
                employee.getId(),
                employee.getFirstName(),
                employee.getLastName(),
                employee.getEmail(),
                employee.getPhone(),
                employee.getDepartment(),
                employee.getJobTitle(),
                employee.getSalary(),
                employee.getHireDate(),
                employee.getStatus(),
                employee.getCreatedAt(),
                employee.getUpdatedAt());
    }
}
